<script setup>
import Table from './Table.vue';

const title = 'Promo Sales';

const fields = [
  {
    title: '',
    color: 'dark-blue',
  },
  {
    title: 'Financial Performance',
    color: 'dark-blue',
    dataFields: [
      {
        title: 'Total Revenue',
        subtitle: 'Revenue',
        tooltip: 'Total Revenue',
        format: 'currency',
        scale: 0,
      },
      {
        title: 'ARPU',
        subtitle: 'N/A',
        tooltip: 'Revenue / (WLs + DIs)',
        format: 'currency',
        scale: 0,
      },
      {
        title: 'VC % of Rev',
        subtitle: 'Discuss',
        tooltip: 'Total VC / Total Revenue',
        format: 'percent',
        scale: 0,
      },
    ],
  },
  {
    title: 'Lesson Performance',
    color: 'blue',
    dataFields: [
      {
        title: 'ATLs',
        subtitle: 'Enrollment Status',
        tooltip: '',
        format: 'integer',
      },
      {
        title: 'AWLs',
        subtitle: 'Enrollment History',
        format: 'integer',
      },
      {
        title: 'Net Lessons',
        subtitle: 'Enrollment History',
        tooltip: 'Lessons Started - Lessons Stopped',
        format: 'integer',
      },
      {
        title: 'Churn Rate',
        subtitle: 'Enrollment History',
        tooltip: 'Lessons Stopped / AWLs',
        format: 'percent',
        scale: 2,
      },
    ],
  },
  {
    title: 'Trial Performance',
    color: 'light-blue',
    dataFields: [
      {
        title: 'Attended Trials',
        subtitle: 'Scheduled Trials',
        format: 'integer',
      },
      {
        title: 'Total Trial Conversions',
        subtitle: 'Scheduled Trials',
        tooltip: 'Trials Converted / Trials Attended',
        format: 'integer',
      },
    ],
  },
  {
    title: 'Operational Performance',
    color: 'yellow',
    dataFields: [
      {
        title: 'Deployed Capacity',
        subtitle: 'Capacity Planning',
        tooltip: 'Deployed Capacity',
        format: 'decimal',
        scale: 1,
      },
      {
        title: 'ATL Capacity Utilization',
        subtitle: 'Enrollment Status',
        tooltip: 'ATL / Deployed Capacity',
        format: 'percent',
        scale: 2,
      },
      {
        title: 'AQL Capacity Utilization',
        subtitle: 'Enrollment Status',
        tooltip: 'AWL / Deployed Capacity',
        format: 'percent',
        scale: 2,
      },
      {
        title: 'NPS Score',
        subtitle: 'Listen360',
        tooltip: '1-Month NPS or 3-Month NPS?',
        format: 'decimal',
        scale: 2,
      },
    ],
  },
];

const data = [
  {
    month: 'Aug',
    totalRevenue: 90.5,
    arpu: 100,
    vcPctOfRevenue: 0.9,
    atls: 10,
    awls: 10,
    netLessons: 0.5,
    churnRate: 0.08,
    attendedTrials: 15,
    totalTrialConverstions: 9,
    deployedCapacity: 108,
    atlCapacityUtilization: 0.5,
    awlCapacityUtilization: 0.5,
    npsScore: 75,
  },
  {
    month: 'Jul',
    totalRevenue: 90.5,
    arpu: 100,
    vcPctOfRevenue: 0.9,
    atls: 10,
    awls: 10,
    netLessons: 0.5,
    churnRate: 0.08,
    attendedTrials: 15,
    totalTrialConverstions: 9,
    deployedCapacity: 108,
    atlCapacityUtilization: 0.5,
    awlCapacityUtilization: 0.5,
    npsScore: 75,
  },
  {
    month: 'Jun',
    totalRevenue: 90.5,
    arpu: 100,
    vcPctOfRevenue: 0.9,
    atls: 10,
    awls: 10,
    netLessons: 0.5,
    churnRate: 0.085,
    attendedTrials: 15,
    totalTrialConverstions: 9,
    deployedCapacity: 108,
    atlCapacityUtilization: 0.5,
    awlCapacityUtilization: 0.5,
    npsScore: 75,
  },
  {
    month: 'May',
    totalRevenue: 90.5,
    arpu: 100,
    vcPctOfRevenue: 0.9,
    atls: 10,
    awls: 10,
    netLessons: 0.5,
    churnRate: 0.08,
    attendedTrials: 15,
    totalTrialConverstions: 9,
    deployedCapacity: 108,
    atlCapacityUtilization: 0.5,
    awlCapacityUtilization: 0.5,
    npsScore: 75,
  },
  {
    month: 'Apr',
    totalRevenue: 90.5,
    arpu: 100,
    vcPctOfRevenue: 0.9,
    atls: 10,
    awls: 10,
    netLessons: 0.5,
    churnRate: 0.057,
    attendedTrials: 15,
    totalTrialConverstions: 9,
    deployedCapacity: 108,
    atlCapacityUtilization: 0.5,
    awlCapacityUtilization: 0.5,
    npsScore: 75,
  },
  {
    month: 'Mar',
    totalRevenue: 90.5,
    arpu: 100,
    vcPctOfRevenue: 0.9,
    atls: 10,
    awls: 10,
    netLessons: 0.5,
    churnRate: 0.08,
    attendedTrials: 15,
    totalTrialConverstions: 9,
    deployedCapacity: 108,
    atlCapacityUtilization: 0.5,
    awlCapacityUtilization: 0.5,
    npsScore: 75,
  },
  {
    month: 'Feb',
    totalRevenue: 90.5,
    arpu: 100,
    vcPctOfRevenue: 0.9,
    atls: 10,
    awls: 10,
    netLessons: 0.5,
    churnRate: 0.08,
    attendedTrials: 15,
    totalTrialConverstions: 9,
    deployedCapacity: 108,
    atlCapacityUtilization: 0.5,
    awlCapacityUtilization: 0.5,
    npsScore: 75,
  },
  {
    month: 'Jan',
    totalRevenue: 90.5,
    arpu: 100,
    vcPctOfRevenue: 0.9,
    atls: 10,
    awls: 10,
    netLessons: 0.5,
    churnRate: 0.08,
    attendedTrials: 15,
    totalTrialConverstions: 9,
    deployedCapacity: 108,
    atlCapacityUtilization: 0.5,
    awlCapacityUtilization: 0.5,
    npsScore: 75,
  },
];
</script>

<template>
  <main>
    <Table :fields="fields" :data="data" />
  </main>
</template>
